---
title: "Get Along with Yourself"
author: "Yiwen"
date: "2019-02-08T21:49:57-07:00"
output: html_document
categories:
  - Blogs
tags:
  - 玄学
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Do you get along with yourself?


Once I was told that “one should learn how to get along with himself” There is an old saying goes “Being alone enables a person to become independent and strong.”

Facts from nature: some animal species survive by the gregarious characteristics, these animals include wolves, lions, elephants, etc. The collective way of preying and inhabiting is probably the best way to survive and incubate for the offsprings in the wild environment.

Same concept can be applied to human beings. Think back to when we are little kids, under the parenting protection, our parents always give their best to us. The care, love and support they devote to us made us better people. My father used to tell me “I raise you not because it’s part of my parent responsibility, but the responsibility to the community. My bottom line is that you don’t do anything that harms the society.” Those words always crack me up. Because first, I think his goal has accomplished; second, I think he was talking to an inmate, instead of his own blood. 

To become a better professional, we all have our own techniques. In the Eastern world communities, people like to mixed life which combines "life life and "work life". For a typical example, my friends are those whom I work with. However, that is not true in the Western world. Westerners like to separate their work from their life. There is this clear boundary which clearly states “work” on the left, and “life” on the right. I think this is quite effective in terms of getting work done and living a individual life. 


